# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
cases:
    - decl: |-
          // Promise in function argument, no error
          function foo(r: Promise<int>): int {
              return await r
          }
          function bar(p: int): int {
              return p + 1
          }
      use: |-
          assert foo(launch bar(1)) == 2

    - decl: |-
          // Error in launch function propagates outside
          function foo(r: Promise<int>): int {
              return await r
          }
          function bar(p: int): int {
              if (p == 1) {
                  throw new Error('ABC')
              }
              return p + 1
          }
      use: |-
          try {
              foo(launch bar(1))
              assert false
          } catch (e: Error) {
              assert e.message == 'ABC'  // expected
          } catch (e) {
              assert false
          }

    - decl: |-
          // Error in await function propagates outside
          function foo(r: Promise<int>, p: int): int {
              if (p == 1) {
                  throw new Error('ABC')
              }
              return await r
          }
          function bar(p: int): int {
              return p + 1
          }
      use: |-
          try {
              foo(launch bar(1), 1)
              assert false
          } catch (e: Error) {
              assert e.message == 'ABC'  // expected
          } catch (e) {
              assert false
          }

    - decl: |-
          // Exception in launch function propagates outside
          function foo(r: Promise<int>): int throws {
              return await r
          }
          function bar(p: int): int throws {
              if (p == 1) {
                  throw new Exception('ABC')
              }
              return p + 1
          }
      use: |-
          try {
              foo(launch bar(1))
              assert false
          } catch (e: Exception) {
              assert e.message == 'ABC'  // expected
          } catch (e) {
              assert false
          }

    - decl: |-
          // Exception in await function propagates outside
          function foo(p: int, r: Promise<int>): int throws {
              if (p == 1) {
                  throw new Exception('ABC')
              }
              return await r
          }
          function bar(p: int): int throws {
              return p + 1
          }
      use: |-
          try {
              foo(1, launch bar(1))
              assert false
          } catch (e: Exception) {
              assert e.message == 'ABC'  // expected
          } catch (e) {
              assert false
          }

    - decl: |-
          // Exception re-thrown and propagates outside
          function baz(r: Promise<int>, f: (r: Promise<int>) => int throws): int rethrows {
              return f(r)
          }
          function foo(r: Promise<int>): int {
              return await r
          }
          function bar(p: int): int throws {
              if (p == 1) {
                  throw new Exception('ABC')
              }
              return p + 1
          }
      use: |-
          try {
              baz(launch bar(1), foo)
              assert false
          } catch (e: Exception) {
              assert e.message == 'ABC'  // expected
          } catch (e) {
              assert false
          }

    - decl: |-
          // Error in one promise should not affect other running promises
          function foo(p: int): string {
              if (p == 2) {
                  throw new Error('X')
              }
              return `${p}`
          }

          function bar(p: Promise<string>): string {
              try {
                  return await p
              } catch (e: Error) {
                  return e.message
              }
          }

          let arr: Promise<string>[]
      use: |-
          let res = ''
          arr = [launch foo(1), launch foo(2), launch foo(3)]
          for (let v of arr) res += bar(v)
          assert res == '1X3'

    - decl: |-
          // Exception in one promise should not affect other running promises
          function foo(p: int): string throws {
              if (p == 2) {
                  throw new Exception('X')
              }
              return `${p}`
          }

          function bar(p: Promise<string>): string {
              try {
                  return await p
              } catch (e: Exception) {
                  return e.message
              } catch (e) {
                  return '' // should never come here
              }
          }

          let arr: Promise<string>[]
      use: |-
          try {
              let res = ''
              arr = [launch foo(1), launch foo(2), launch foo(3)]
              for (let v of arr) res += bar(v)
              assert res == '1X3'
          } catch (e) {
              assert false
          }

    - decl: |-
          function foo(p: string): string {
              return p + p
          }
          class A {
              fld: Promise<string>
              constructor() {
                  this.fld = launch foo('')
                  await this.fld
              }
              constructor(p: Promise<string>) {
                  this.fld = p
              }
              meth(): Promise<string> {
                  return this.fld
              }
          }
          function p1(): Promise<string>|null|undefined { return launch foo('A') }
          function p2(): Promise<string>|null|undefined { return null }
      use: |-
          // array element
          let arr: Promise<string>[] = [launch foo('A')]
          assert (await arr[0]) == 'AA'

          // tuple element
          let tup: [boolean, Promise<string>] = [false, launch foo('A')]
          assert (await tup[1]) == 'AA'

          // union type
          let ut: boolean|number|Promise<string> = launch foo('A')
          assert (await (ut as Promise<string>)) == 'AA'

          // nullish type
          let nt: Promise<string>|null|undefined = p1()
          assert (await nt!) == 'AA'

          nt = p2()
          try {
              await nt!
              assert false
          } catch (e) {
              // OK
          }

          // function call
          let f: (p: Promise<string>) => Promise<string> = (p: Promise<string>): Promise<string> => p
          assert (await f(launch foo('A'))) == 'AA'

          // instance field
          let a: A = { fld: launch foo('A') }
          assert (await a.fld) == 'AA'

          // method call
          let b: A = new A(launch foo('A'))
          assert (await b.meth()) == 'AA'

          // conditional expression
          let expr1 = launch foo('A')
          let expr2 = launch foo('B')
          assert (await a instanceof A ? expr1 : expr2) == 'AA'
          assert (await ! (a instanceof A) ? expr1 : expr2) == 'BB'
